spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=${USER_DB_USERNAME}
spring.datasource.password=${USER_DB_PASSWORD}
jwt.secret=${USER_SERVICE_SECRET_KEY}
jwt.expiration=3600000