server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
jwt:
  secret: ${INVESTMENT_TRACKER_JWT_SECRET}
  expiration: 3600000
