spring:
  application:
    name: analytics-service

server:
  port: 8087

jwt:
  secret: ${INVESTMENT_TRACKER_JWT_SECRET}

services:
  portfolio:
    base-url: ${PORTFOLIO_SERVICE_URL}
  market:
    base-url: ${MARKET_DATA_SERVICE_URL}
  credit:
    base-url: ${CREDIT_SERVICE_URL}
