server:
  port: 8081
spring:
  application:
    name: portfolio-service

  datasource:
    username: ${PORTFOLIO_DB_USERNAME}
    password: ${PORTFOLIO_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${PORTFOLIO_SERVICE_SECRET_KEY}

